### ISSUE TITLE
Workflow is getting mixed up between Alfred 2 in Application Support and Alfred 3

### ISSUE THREAD

**Issue by ghost** [stuartcryan/rapid-browser-tabs-for-alfred#15]
I am unable to change the config to `/Users/tiffanywhite/Dropbox/RBT/` or to `/Library/Application Support/Alfred 3/Workflow Data/com.stuartryan.alfred.rapidbrowsertabs/` as it automatically defaults to `/Library/Application Support/Alfred 2/Workflow Data/com.stuartryan.alfred.rapidbrowsertabs/`. I have deleted the Alfred 2 folder, yet, RBT recreates it. I've set up the config the way I needed to but no luck.

Not sure if I can fix it with my limited knowledge. Can you fix it?

Thanks.

**Comment by jondeodat** [comment]
Same problem here. Doesn't work at all out the box and the config is saved/recreated all the times in Alfred 2 folder even if it doesn't exist.

**Comment by rpgoldman** [comment]
I am running Alfred 3, and find that RBT *does* dump its configuration in the `/Alfred 2/` folder, as @twhite96 reports, but this isn't breaking things for me: I think the configuration file location is hard-coded, so that the workflow finds its configuration even though it's officially in the wrong place.

**Comment by rpgoldman** [comment]
I could easily fix this and provide a merge request that would change the location to `Alfred 3` from `Alfred 2` (it's hard-coded in).  But I don't know if this is the right thing -- are there people out there still running Alfred 2 for whom that would be a hardship?  If so, should we look for the Alfred 3 directory first, and put the config in Alfred 2 if it's unfound?

**Comment by ghost** [comment]
Closing this as their hasn't been any conversation about it plus Alfred is on v4
