### ISSUE TITLE
Non-latin query error

### ISSUE THREAD

**Issue by pochemuto** [stuartcryan/rapid-browser-tabs-for-alfred#6]
```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: load_list.rb:53:in `=~': incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string) (Encoding::CompatibilityError)
    from load_list.rb:53:in `tab_matches_title?'
    from load_list.rb:59:in `tab_matches_query?'
    from load_list.rb:195:in `block in <main>'
    from load_list.rb:194:in `each'
    from load_list.rb:194:in `<main>'
```

**Comment by stuartcryan** [comment]
Thanks for the submission, I will have a look into this but I may be in need of searching for someone who is an absolute GOD with regex to fix this as the regex I had to use is immensely complex (and even I only understand it to a point).

Therefore if there is anyone that is a regex guru and might be able to help out please get in touch. I will have a look in the mean time however.
Cheers,
Stuart
